### ISSUE TITLE
Turbolift doors unlocked - Multiple decks

### ISSUE THREAD

**Issue by VigoHornblower** [dapperrobotbear/Stage9#106]
Turbolifts that aren't on the destinations list still open and spawn. The only locked turbolift door I could find was on deck 36.

**Comment by scragnog** [comment]
Fixed on deck 9.

If anyone else is able to let us know where any more disconnected turbolifts are, please reply to this issue.

**Comment by VigoHornblower** [comment]
I'm going through deck by deck to find them. Here's the first couple:
![deck3-5](https://user-images.githubusercontent.com/34043160/33352927-388d3046-d479-11e7-9994-2ee153a09894.jpg)

**Comment by VigoHornblower** [comment]
Deck 9 (just in case you missed one)
![deck8-9](https://user-images.githubusercontent.com/34043160/33353611-9d19724c-d47c-11e7-8904-c88ea6653bae.jpg)

**Comment by VigoHornblower** [comment]
Deck 10
![deck10-11](https://user-images.githubusercontent.com/34043160/33353871-fc50d65a-d47d-11e7-81c9-88f5fdf7b99a.jpg)

**Comment by Gary-Baggins** [comment]
unable to find any turbo lift doors without a lift behind them, please close @TheStrato @HPringles
