### ISSUE TITLE
V0010-QA1 Accidentally activate warp core breach , results in unreal engine crash. [Main Engineering] 

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#251]
In main engineering you can activate a warp core overload 'which sounds like a Klingon alert' without any menu system or warning. Also a engineer starts dancing on the upper level warp core when its activated. 

The warp core explodes to a white screen but UE3 engine crashes. Error attached.

You should bel able to have a menu to activate warp core breach, stop, eject core etc. 

Mac OS High Sierra 10.3.13

[Side note: Plus not easy to see where to eject warp core itself]

```
LoginId:2389ca07914a64dd3c1d9ba38a1e5d89
EpicAccountId:

 SEGV_MAPERR at 0x3

FGenericPlatformMisc::RaiseException(unsigned int) Address = 0x104c09dab (filename not found) [in Stage9]
FOutputDevice::Logf(wchar_t const*, ...) Address = 0x104d0842d (filename not found) [in Stage9]
FDebug::AssertFailed(char const*, char const*, int, wchar_t const*, ...) Address = 0x104cd1254 (filename not found) [in Stage9]
FAsyncLoadingThread::TickAsyncThread(bool, bool, float, bool&, FFlushTree*) Address = 0x104d71a71 (filename not found) [in Stage9]
FAsyncLoadingThread::Run() Address = 0x104d730cf (filename not found) [in Stage9]
FRunnableThreadPThread::Run() Address = 0x104c2d36a (filename not found) [in Stage9]
FRunnableThreadPThread::_ThreadProc(void*) Address = 0x104c1ac16 (filename not found) [in Stage9]
_pthread_body Address = 0x7fff5ccb46c1 (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff5ccb456d (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff5ccb3c5d (filename not found) [in libsystem_pthread.dylib]
```

**Comment by HPringles** [comment]
# Mac Specific Issue 

*** Not reproducible on windows***

**Comment by Jaredsfs1** [comment]
I repeated this myself,  it's not just accidental triggering, whenever I click on Geordi's station to start the core breach, the whole thing runs through perfectly, but at the white screen my game crashes out.  Attaching log here:

```
LoginId:2ead80538140a6425e4e9fb724d89a41
EpicAccountId:

 SEGV_MAPERR at 0x3

FGenericPlatformMisc::RaiseException(unsigned int) Address = 0x10e5d2dab (filename not found) [in Stage9]
FOutputDevice::Logf(wchar_t const*, ...) Address = 0x10e6d142d (filename not found) [in Stage9]
FDebug::AssertFailed(char const*, char const*, int, wchar_t const*, ...) Address = 0x10e69a254 (filename not found) [in Stage9]
FAsyncLoadingThread::TickAsyncThread(bool, bool, float, bool&, FFlushTree*) Address = 0x10e73aa71 (filename not found) [in Stage9]
FAsyncLoadingThread::Run() Address = 0x10e73c0cf (filename not found) [in Stage9]
FRunnableThreadPThread::Run() Address = 0x10e5f636a (filename not found) [in Stage9]
FRunnableThreadPThread::_ThreadProc(void*) Address = 0x10e5e3c16 (filename not found) [in Stage9]
_pthread_body Address = 0x7fff56f6f6c1 (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff56f6f56d (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff56f6ec5d (filename not found) [in libsystem_pthread.dylib]
```


Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by jgbr** [comment]
I think it does need to clear how to activate the warp core breach but also stop it. The crash being the critical part.

**Comment by dapperrobotbear** [comment]
Also the doors are blocked off with an invisible wall to keep the player from escaping when they activate this sequence. At least for the time being.

**Comment by jgbr** [comment]
@TheStrato Mac issue

**Comment by dapperrobotbear** [comment]
Is this still crashing in QA2?

**Comment by jgbr** [comment]
Yes. I will retest again if you like by loading fresh and going straight there.

**Comment by TheStrato** [comment]
Done.

**Comment by jgbr** [comment]
error still present

LoginId:2389ca07914a64dd3c1d9ba38a1e5d89
EpicAccountId:

 SEGV_MAPERR at 0x3

FGenericPlatformMisc::RaiseException(unsigned int) Address = 0x102178dab (filename not found) [in Stage9]
FOutputDevice::Logf(wchar_t const*, ...) Address = 0x10227742d (filename not found) [in Stage9]
FDebug::AssertFailed(char const*, char const*, int, wchar_t const*, ...) Address = 0x102240254 (filename not found) [in Stage9]
FAsyncLoadingThread::TickAsyncThread(bool, bool, float, bool&, FFlushTree*) Address = 0x1022e0a71 (filename not found) [in Stage9]
FAsyncLoadingThread::Run() Address = 0x1022e20cf (filename not found) [in Stage9]
FRunnableThreadPThread::Run() Address = 0x10219c36a (filename not found) [in Stage9]
FRunnableThreadPThread::_ThreadProc(void*) Address = 0x102189c16 (filename not found) [in Stage9]
_pthread_body Address = 0x7fff5ccb46c1 (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff5ccb456d (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff5ccb3c5d (filename not found) [in libsystem_pthread.dylib]

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
