### ISSUE TITLE
V0010-QA1 After saucer separation stuff is left behind

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#332]
**Summary**

When flying out of the main shuttlebay, and triggering a saucer separation by remotely opening shuttlebay 2 and then separating the saucer from within the shuttle, all the corridors of deck 3 and 4 stay behind (but eventually disappear possibly because shuttlebay 2 is loaded instead), and the phaser ranges, turbolift, and transporter room 2 are visible permanently.

***What is the expected correct behavior?***

Once saucer separation is initiated, all objects within the saucer should be despawned.

**Steps to reproduce**

1. Fly out of the main shuttlebay
2. Remotely open shuttlebay 2 from within the shuttle
3. Separate the saucer from within the shuttle

**Relevant logs and/or screenshots**

![jetsam](https://user-images.githubusercontent.com/37262529/37341422-f05575e4-2686-11e8-9f2c-9442e44016d9.png)

**Possible fixes**

Once saucer separation is inititiated, since it seems it's impossible to be on the saucer for the time being, unload everything in the saucer section.

MacBook Air (13-inch, Early 2015)
OS: macOS High Sierra (10.13.3)
Processor: 1.6 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Video: Intel HD Graphics 6000 1536 MB

**Comment by jgbr** [comment]
Maybe related to 331.

@HPringles Mac and graphics,

**Comment by jgbr** [comment]
![untitled](https://user-images.githubusercontent.com/37260734/37359349-4314a012-26e5-11e8-8082-f27822e9c67b.jpeg)

turbolift!

**Comment by scragnog** [comment]
I believe the instanced rooms not despawning is resolved now. @dapperrobotbear can you confirm?

**Comment by dapperrobotbear** [comment]
The emergency turbolift was part of the persistent map. But you moved it to Deck 1 for now, so that should fix it.

**Comment by dapperrobotbear** [comment]
Also the level instances were fixed in QA2

**Comment by Gary-Baggins** [comment]
Not fixed @dapperrobotbear @scragnog 
Previously activated shuttle present along with multiple corridors and one turbo lift.

**Comment by scragnog** [comment]
@Gary-Baggins the shuttle issue we are aware of and has no fix-date currently (we need to rejig the way this works), can you confirm what deck you were seeing the corridors for (or take a screenshot) as saucer decks should always be unloaded when you perform a saucer separation. Same with the turbolift, where was this?

**Comment by Gary-Baggins** [comment]
The turbo lift would be Shuttlebay 1 bow (the one I took to the MSB) which I believe is mislabelled,
https://cdn.discordapp.com/attachments/422132672178159616/423852829749411851/unknown.png
https://cdn.discordapp.com/attachments/422132672178159616/423853653695266817/unknown.png

**Comment by dapperrobotbear** [comment]
@scragnog when we do a saucer sep we need to unload all decks through the game mode.

**Comment by scragnog** [comment]
should be all fixed now

**Comment by mikebarber1** [comment]
v10 hf does not allow you to separate while the main shuttle bay door is open - so "fixed" it is

**Comment by Gary-Baggins** [comment]
I want to confirm whether this is an issue on Linux or not before closing @TheStrato @HPringles

**Comment by TheStrato** [comment]
Standing by for Linux test.

**Comment by Rekkert** [comment]
Confirmed fixed on Linux as well

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
