### ISSUE TITLE
Win - V0010-QA2 Bridge Engineering Console side panel missing.

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#368]
When activating the rear engineering console on the bridge, only the back panel activates.

To be canon the side panel should also light up with further controls. [Possibly after Season 2]

![untitled](https://user-images.githubusercontent.com/37260734/37421073-4ab999f0-27b0-11e8-8ca3-d0ede846e081.jpeg)

![galaxy_bridge_engineering](https://user-images.githubusercontent.com/37260734/37421289-d3492dbc-27b0-11e8-9494-51d3ca3c742c.jpg)

I couldn't find better pictures.

**Comment by jgbr** [comment]
@HPringles enhancement

**Comment by jgbr** [comment]
Im also wondering about the dimensions of that whole back panel as in the picture it looks wider to fit that panel in......

**Comment by scragnog** [comment]
added now in the last batch of lcars for the new season 7 bridge. That particular graphic only shows when you enable the console (as it does on the show)

**Comment by jeppelykke** [comment]
@scragnog Confirmed fixed for windows

**Comment by Sciencekeeper** [comment]
@TheStrato fixed btw AWESOME activating that console!

**Comment by TheStrato** [comment]
Resolved. Closing ticket.

**Comment by Gary-Baggins** [comment]
@TheStrato not fixed.
![image](https://user-images.githubusercontent.com/35035873/37554158-8f7f6f74-29cc-11e8-8b51-0d38e980fd64.png)

**Comment by jgbr** [comment]
fixed on Mac
