### ISSUE TITLE
V0010-QA4 - Party Mode Sound Error

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#401]
**Summary**
When playing party mode the sound from the video is played from the center of the bridge and cannot be heard directly infront of the viewscreen or from certain areas at the rear of the bridge.

The sound is also stereo/surround and changes position in headphones which is very disorientating

***What is the expected correct behavior?***
The sound should play the same in every space on the bridge and not change with player rotation

**Steps to reproduce**

1. Start the part mode on the bridge
2. Move from the center to the very front(by the viewscreen) the sound will cut out
3. Move to the rear , by the HEAD door, the sound will also cut out/
4. When wearing a headset that supports stereo or surround, turn the player's body and notice the difference

**Comment by Gary-Baggins** [comment]
Confirmed @TheStrato @HPringles

**Comment by scragnog** [comment]
this should be fixed now, there's a strange minor issue where the channels invert if you go right up to the viewscreen, but other than that, should be sorted.

**Comment by EazyCheeze1978** [comment]
Unfortunately not fixed. Audio still cuts out directly in front of the viewscreen and by the Head door.

**Comment by TheStrato** [comment]
Push. Will examine in later versions.

**Comment by jgbr** [comment]
Works fine on Mac [GM]
